# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinelearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='text1',
            field=models.CharField(default='text', max_length=100),
            preserve_default=False,
        ),
    ]
