# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-18 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinelearning', '0002_file_text1'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.FileField(default='this tianjia de column', upload_to=''),
            preserve_default=False,
        ),
    ]
