# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-19 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinelearning', '0004_auto_20170319_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
    ]
